apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: house-automation
resources:
 - namespace.yaml
 - nodered.yaml
 - mqtt.yaml
configMapGenerator:
  - name: house-automation-nodered-config-settings
    files:
      - settings.js
  - name: house-automation-nodered-config-flows
    files:
      - flows.json
  - name: house-automation-nodered-config-mqtt-service
    literals:
      - mqtt-service="dev-house-automation-mqtt-service"
  - name: house-automation-mosquitto-config-settings
    files:
      - mosquitto.conf
