apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: house-automation
resources:
 - namespace.yaml
 - nodered.yaml
 - mqtt.yaml
configMapGenerator:
  - name: house-automation-nodered-config-settings
    files:
      - settings.js
  - name: house-automation-nodered-config-flows
    files:
      - flows.json
