apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: house-automation-nodered-ingress
  labels:
    component: house-automation-nodered
spec:
  ingressClassName: public
  rules:
  - host: nodered.home.seifts.us
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: house-automation-nodered-service
            port:
              number: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: house-automation-nodered-service
  labels:
    component: house-automation-nodered
spec:
  ports:
  - protocol: TCP
    port: 1880
    targetPort: 1880
  selector:
    component: house-automation-nodered
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-automation-nodered-deployment
  labels:
    component: house-automation-nodered
spec:
  selector:
    matchLabels:
      component: house-automation-nodered
  replicas: 1
  template:
    metadata:
      labels:
        component: house-automation-nodered
    spec:
      containers:
        - name: house-automation-nodered-image
          image: nodered/node-red:2.2.3-12
          ports:
            - containerPort: 1880
          volumeMounts:
            - name: house-automation-nodered-settings
              mountPath: /data/settings.js
              subPath: settings.js
              readOnly: true
            - name: house-automation-nodered-flows
              mountPath: /data/flows.json
              subPath: flows.json
              readOnly: true
      volumes:
        - name: house-automation-nodered-settings
          configMap:
            name: house-automation-nodered-config-settings
        - name: house-automation-nodered-flows
          configMap:
            name: house-automation-nodered-config-flows
