apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: house-automation-nodered-ingress
  labels:
    component: house-automation-nodered
spec:
  ingressClassName: public
  rules:
  - host: nodered.home.seifts.us
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: house-automation-nodered-service
            port:
              number: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: house-automation-nodered-service
  labels:
    component: house-automation-nodered
spec:
  ports:
  - protocol: TCP
    port: 1880
    targetPort: 1880
  selector:
    component: house-automation-nodered
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-automation-nodered-deployment
  labels:
    component: house-automation-nodered
spec:
  selector:
    matchLabels:
      component: house-automation-nodered
  replicas: 1
  template:
    metadata:
      labels:
        component: house-automation-nodered
    spec:
      containers:
        - name: house-automation-nodered-image
          image: nodered/node-red:2.2.3-12
          ports:
            - containerPort: 1880
#          volumeMounts:
#            - name: house-automation-nodered-storage
#              mountPath: /data
#      volumes:
#        - name: house-automation-nodered-storage
#          persistentVolumeClaim:
#            claimName: house-automation-nodered-pvc
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: house-automation-nodered-pvc
#  labels:
#    component: house-automation-nodered
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Mb
